apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-redis
  labels:
    app: voting-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-redis
  template:
    metadata:
      labels:
        app: voting-redis
    spec:
      containers:
        - name: voting-redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
      volumes:
        - name: redis-data
          emptyDir: {}