apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-client
  labels:
    app: voting-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-client
  template:
    metadata:
      labels:
        app: voting-client
    spec:
      containers:
        - name: voting-client
          image: udarawick/voting-client:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: voting-client-config